#!/usr/bin/env python3
"""Thrixel -> Roblox asset sync.

One command gets every mesh under thrixel_assets/ into the open Studio place:

    python3 tools/roblox_helpers.py sync [--only Name ...] [--user-id N] > swap.luau

It uploads new or changed meshes to Open Cloud (content-hash cached, so re-runs
never re-upload), rewrites src/shared/AssetIds.luau, and prints one Luau chunk
to stdout (progress goes to stderr). Run that chunk through execute_luau
(datamodel_type "Edit"): it inserts missing models into ReplicatedStorage.Assets,
replaces stale ones, and sets the edit-time MeshPart properties clones inherit.
Idempotent end to end — re-running both steps is always safe.

Layout: one directory per asset, `thrixel_assets/<Name>/`. The directory name is
the asset's identity; inside it the newest .fbx wins, else the newest .glb.
Needs `roblox_api_key.txt` in the project root, and (first upload only) the
creator user id via --user-id or ROBLOX_USER_ID — get it with
`execute_luau: return game.CreatorId`.
"""

import json
import os
import re
import ssl
import sys
import time
import urllib.error
import urllib.request
import uuid
from hashlib import sha1
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSET_DIR = ROOT / "thrixel_assets"
KEY_FILE = ROOT / "roblox_api_key.txt"
MANIFEST = ROOT / "assets" / "manifest.json"
OUT_LUAU = ROOT / "src" / "shared" / "AssetIds.luau"

API_CREATE = "https://apis.roblox.com/assets/v1/assets"
API_OP = "https://apis.roblox.com/assets/v1/operations/{}"
CONTENT_TYPES = {".glb": "model/gltf-binary", ".fbx": "model/fbx"}
MAX_BYTES = 20 * 1024 * 1024

_SSL = ssl.create_default_context()

LUAU_HEADER = """--!strict
-- AssetIds — GENERATED by tools/roblox_helpers.py sync. Do not edit by hand.
return {
"""

SWAP_TEMPLATE = """local InsertService = game:GetService("InsertService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local ASSETS = {
__ASSETS__
}

local folder = ReplicatedStorage:FindFirstChild("Assets")
if not folder then
\tfolder = Instance.new("Folder")
\tfolder.Name = "Assets"
\tfolder.Parent = ReplicatedStorage
end

local log = {}
for _, entry in ipairs(ASSETS) do
\tlocal name, id = entry[1], entry[2]
\tlocal existing = folder:FindFirstChild(name)
\tif existing and existing:GetAttribute("AssetId") == id then
\t\ttable.insert(log, name .. ": up to date")
\t\tcontinue
\tend
\tif existing then
\t\texisting:Destroy()
\tend
\tlocal ok, result = pcall(InsertService.LoadAsset, InsertService, id)
\tif not ok then
\t\ttable.insert(log, name .. ": FAILED " .. tostring(result):sub(1, 90))
\t\tcontinue
\tend
\t-- LoadAsset wraps the uploaded Model in a container Model; unwrap one level.
\tlocal inner = result:GetChildren()[1]
\tlocal model = if inner and inner:IsA("Model") then inner else result
\tmodel.Name = name
\tmodel:SetAttribute("AssetId", id)
\tlocal meshes = 0
\tfor _, d in ipairs(model:GetDescendants()) do
\t\tif d:IsA("MeshPart") then
\t\t\td.CollisionFidelity = Enum.CollisionFidelity.Box
\t\t\td.RenderFidelity = Enum.RenderFidelity.Automatic
\t\t\td.Anchored = true
\t\t\td.CanCollide = false
\t\t\td.CanTouch = false
\t\t\tmeshes += 1
\t\tend
\tend
\tmodel.Parent = folder
\tif model ~= result then
\t\tresult:Destroy()
\tend
\tlocal _, size = model:GetBoundingBox()
\ttable.insert(log, string.format("%s: swapped in, %d meshparts, bbox %.1f x %.1f x %.1f studs",
\t\tname, meshes, size.X, size.Y, size.Z))
end
table.insert(log, "Assets folder holds " .. #folder:GetChildren() .. " models.")
return table.concat(log, "\\n")
"""


def log(msg):
    """Print a progress line to stderr, keeping stdout clean for the Luau chunk."""
    print(msg, file=sys.stderr)


def api_key():
    """Return the Open Cloud API key from roblox_api_key.txt.

    Returns:
        The key as a stripped string. Exits with a message if the file is missing.
    """
    if not KEY_FILE.exists():
        sys.exit(f"No API key at {KEY_FILE}")
    return KEY_FILE.read_text().strip()


def load_manifest():
    """Return the upload cache from assets/manifest.json, or {} if absent."""
    return json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}


def save_manifest(manifest):
    """Write the upload cache back to assets/manifest.json."""
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True))


def find_mesh(directory):
    """Pick the mesh file to upload for one asset directory.

    FBX keeps part names and Architect flat colours; GLB keeps full PBR maps.
    Which format an asset uses is chosen by which file is in its directory.

    Args:
        directory: The `thrixel_assets/<Name>/` directory.

    Returns:
        The newest .fbx in the directory if any, else the newest .glb
        (searching subdirectories too), else None.
    """
    fbx = list(directory.glob("*.fbx"))
    if fbx:
        return max(fbx, key=lambda p: p.stat().st_mtime)
    glbs = list(directory.glob("*.glb")) or list(directory.rglob("*.glb"))
    return max(glbs, key=lambda p: p.stat().st_mtime) if glbs else None


def resolve_user_id(cli_value):
    """Resolve the creator user id for uploads.

    Checks, in order: the --user-id flag, the ROBLOX_USER_ID env var, and the
    `_userId` cached in the manifest. Whatever is found is cached back into the
    manifest so later runs need nothing.

    Args:
        cli_value: The --user-id argument, or None.

    Returns:
        The user id as a string. Exits with instructions if none is available.
    """
    manifest = load_manifest()
    uid = cli_value or os.environ.get("ROBLOX_USER_ID") or manifest.get("_userId")
    if not uid:
        sys.exit(
            "No creator user id. Get it via execute_luau (`return game.CreatorId`) "
            "and pass --user-id N (cached after the first run)."
        )
    if manifest.get("_userId") != str(uid):
        manifest["_userId"] = str(uid)
        save_manifest(manifest)
    return str(uid)


def _multipart(fields, file_field, path, ctype):
    boundary = f"----claude{uuid.uuid4().hex}"
    out = bytearray()
    for key, value in fields.items():
        out += f"--{boundary}\r\n".encode()
        out += f'Content-Disposition: form-data; name="{key}"\r\n\r\n'.encode()
        out += value.encode() + b"\r\n"
    out += f"--{boundary}\r\n".encode()
    out += (
        f'Content-Disposition: form-data; name="{file_field}"; '
        f'filename="{path.name}"\r\n'
    ).encode()
    out += f"Content-Type: {ctype}\r\n\r\n".encode()
    out += path.read_bytes() + b"\r\n"
    out += f"--{boundary}--\r\n".encode()
    return bytes(out), f"multipart/form-data; boundary={boundary}"


def _request(url, data=None, ctype=None, method="GET"):
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("x-api-key", api_key())
    if ctype:
        req.add_header("Content-Type", ctype)
    try:
        with urllib.request.urlopen(req, context=_SSL, timeout=180) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")
        raise RuntimeError(f"HTTP {e.code} from {url}\n{body}") from None


def upload(path, display_name, user_id):
    """Upload one mesh to Open Cloud and wait for the import to finish.

    Args:
        path: The .glb or .fbx file.
        display_name: Roblox-side display name for the asset.
        user_id: Creator user id for the upload's creationContext.

    Returns:
        The new asset id as a string.

    Raises:
        RuntimeError: On an unsupported extension, an API error, an import
            failure, or a poll timeout (10 minutes).
    """
    ctype = CONTENT_TYPES.get(path.suffix.lower())
    if not ctype:
        raise RuntimeError(f"Unsupported extension {path.suffix}")

    request_json = json.dumps(
        {
            "assetType": "Model",
            "displayName": display_name,
            "description": "Generated with Thrixel.",
            "creationContext": {"creator": {"userId": user_id}},
        }
    )
    body, content_type = _multipart({"request": request_json}, "fileContent", path, ctype)
    op = _request(API_CREATE, data=body, ctype=content_type, method="POST")
    op_id = op.get("operationId") or op.get("path", "").split("/")[-1]
    if not op_id:
        raise RuntimeError(f"No operation id in create response: {op}")

    deadline = time.time() + 600
    delay = 2.0
    while time.time() < deadline:
        time.sleep(delay)
        delay = min(delay * 1.3, 15.0)
        result = _request(API_OP.format(op_id))
        if not result.get("done"):
            continue
        if "response" in result:
            state = result["response"].get("moderationResult", {}).get("moderationState")
            if state and "approved" not in state.lower():
                log(f"  ! moderation state: {state}")
            return str(result["response"]["assetId"])
        raise RuntimeError(f"Upload failed: {json.dumps(result.get('error', result))}")
    raise RuntimeError(f"Timed out waiting for operation {op_id}")


def upload_cached(path, display_name, user_id):
    """Upload a mesh unless its exact bytes were uploaded before.

    The cache key is display name plus content hash, so a regenerated asset
    (same name, new bytes) is a real new upload while an unchanged file keeps
    the id it already had.

    Args:
        path: The mesh file.
        display_name: Roblox-side display name, also part of the cache key.
        user_id: Creator user id, used only when an upload actually happens.

    Returns:
        A (asset_id, cached) tuple; cached is True on a cache hit.
    """
    key = f"{display_name}:{sha1(path.read_bytes()).hexdigest()[:16]}"
    manifest = load_manifest()
    if key in manifest:
        return manifest[key]["assetId"], True
    asset_id = upload(path, display_name, user_id)
    manifest = load_manifest()
    manifest[key] = {
        "assetId": asset_id,
        "name": display_name,
        "file": str(path.relative_to(ROOT)) if ROOT in path.parents else str(path),
        "bytes": path.stat().st_size,
    }
    save_manifest(manifest)
    return asset_id, False


def read_asset_ids():
    """Parse src/shared/AssetIds.luau into a {name: asset_id} dict ({} if absent)."""
    if not OUT_LUAU.exists():
        return {}
    pairs = re.findall(
        r'^\s*(\w+)\s*=\s*"rbxassetid://(\d+)"', OUT_LUAU.read_text(), re.MULTILINE
    )
    return dict(pairs)


def write_asset_ids(results):
    """Write the {name: asset_id} table to src/shared/AssetIds.luau for Rojo."""
    lines = [LUAU_HEADER]
    for name in sorted(results):
        lines.append(f'\t{name} = "rbxassetid://{results[name]}",\n')
    lines.append("}\n")
    OUT_LUAU.parent.mkdir(parents=True, exist_ok=True)
    OUT_LUAU.write_text("".join(lines))


def emit_swap_luau(results):
    """Render the Studio-side swap chunk for execute_luau (Edit).

    The chunk is idempotent per asset: a model in ReplicatedStorage.Assets whose
    AssetId attribute matches is skipped; anything else is destroyed, reinserted
    via InsertService:LoadAsset, unwrapped, renamed, stamped with the attribute,
    and has its MeshParts prepared (Box collision, Automatic render fidelity,
    anchored, no collide/touch — all edit-time-only, inherited by clones).

    Args:
        results: {name: asset_id} for every asset in the game.

    Returns:
        The complete Luau source as a string.
    """
    rows = "\n".join(f'\t{{ "{n}", {results[n]} }},' for n in sorted(results))
    return SWAP_TEMPLATE.replace("__ASSETS__", rows)


def sync(only, user_id_arg):
    """Upload changed meshes, rewrite AssetIds.luau, print the swap chunk.

    Args:
        only: Set of asset names to (re)upload, or None for all. Assets outside
            the filter keep their existing ids from AssetIds.luau.
        user_id_arg: The --user-id value, or None. Only resolved if an upload
            actually happens.
    """
    if not ASSET_DIR.exists():
        sys.exit(f"No {ASSET_DIR}")
    dirs = sorted(d for d in ASSET_DIR.iterdir() if d.is_dir())
    if not dirs:
        sys.exit(f"No asset directories in {ASSET_DIR}")

    names = {d.name for d in dirs}
    results = {n: i for n, i in read_asset_ids().items() if n in names}
    uid = None
    problems = []

    for d in dirs:
        if only and d.name not in only:
            continue
        mesh = find_mesh(d)
        if not mesh:
            problems.append(f"{d.name}: no .fbx or .glb found")
            continue
        size = mesh.stat().st_size
        if size > MAX_BYTES:
            problems.append(
                f"{d.name}: {size / 1e6:.1f} MB exceeds the 20 MB Open Cloud limit "
                "— reduce triangles or drop texture_size"
            )
            continue
        display = f"{ROOT.name} {d.name}"
        key = f"{display}:{sha1(mesh.read_bytes()).hexdigest()[:16]}"
        if uid is None and key not in load_manifest():
            uid = resolve_user_id(user_id_arg)
        try:
            asset_id, cached = upload_cached(mesh, display, uid)
            results[d.name] = asset_id
            flag = "cached" if cached else f"uploaded {size / 1e6:.1f} MB"
            log(f"  {d.name:<16} {asset_id}  ({flag})")
        except Exception as exc:  # noqa: BLE001 - report and keep going
            problems.append(f"{d.name}: {exc}")

    write_asset_ids(results)
    log(f"Wrote {OUT_LUAU.relative_to(ROOT)} with {len(results)} assets.")
    print(emit_swap_luau(results))
    log("Swap chunk on stdout — run it through execute_luau (Edit).")

    if problems:
        log(f"{len(problems)} problem(s):")
        for p in problems:
            log(f"  ! {p}")
        sys.exit(1)


def main():
    """Parse arguments and dispatch. Only subcommand: sync."""
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    p_sync = sub.add_parser("sync", help="upload changed meshes and print the swap chunk")
    p_sync.add_argument("--only", nargs="+", metavar="NAME", help="limit to these assets")
    p_sync.add_argument("--user-id", help="creator user id (cached after first use)")
    args = parser.parse_args()
    sync(set(args.only) if args.only else None, args.user_id)


if __name__ == "__main__":
    main()
